version: '3'
services:
  web:
    image: myimage1
    build:
      context: .
    ports:
      - "80:30501"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/var/www/html/index.html


